name: Fetch GreasyFork meta

on:
  schedule:
    - cron: '7 0 * * *'   # UTC 00:07 每日；如需北京时间，可改成 '7 16 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run fetch script
        run: node scripts/fetch-greasyfork.js

      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "actions-bot"
            git config user.email "actions-bot@users.noreply.github.com"
            git add data/warsoul.json
            git commit -m "chore(data): update greasyfork meta"
            git push
          else
            echo "No changes"
          fi